// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNYjBv7sFI2-rweO-fzAvF_fncHB2qxfs',
    appId: '1:50297548634:web:84bf307f6d16d00dfe8d63',
    messagingSenderId: '50297548634',
    projectId: 'otpp-edb0c',
    authDomain: 'otpp-edb0c.firebaseapp.com',
    storageBucket: 'otpp-edb0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN4D6pWiejlsfI4dajp_x3TrBPwDQY378',
    appId: '1:50297548634:android:474551e878b13535fe8d63',
    messagingSenderId: '50297548634',
    projectId: 'otpp-edb0c',
    storageBucket: 'otpp-edb0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzrd4yWWFPCdL4ZaURML21dyW-Rhd2u2s',
    appId: '1:50297548634:ios:5f196e76b5ef01b5fe8d63',
    messagingSenderId: '50297548634',
    projectId: 'otpp-edb0c',
    storageBucket: 'otpp-edb0c.firebasestorage.app',
    iosClientId: '50297548634-je16cqp3ic28jsb1frmj6v7ge5hs070v.apps.googleusercontent.com',
    iosBundleId: 'com.abc.abc.otp.otpp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzrd4yWWFPCdL4ZaURML21dyW-Rhd2u2s',
    appId: '1:50297548634:ios:5f196e76b5ef01b5fe8d63',
    messagingSenderId: '50297548634',
    projectId: 'otpp-edb0c',
    storageBucket: 'otpp-edb0c.firebasestorage.app',
    iosClientId: '50297548634-je16cqp3ic28jsb1frmj6v7ge5hs070v.apps.googleusercontent.com',
    iosBundleId: 'com.abc.abc.otp.otpp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNYjBv7sFI2-rweO-fzAvF_fncHB2qxfs',
    appId: '1:50297548634:web:e43ca9606d4b7420fe8d63',
    messagingSenderId: '50297548634',
    projectId: 'otpp-edb0c',
    authDomain: 'otpp-edb0c.firebaseapp.com',
    storageBucket: 'otpp-edb0c.firebasestorage.app',
  );

}